# Example CORAL-X Config with Simple Emergent Behavior Tracking
# Add these lines to your existing coral_x_*.yaml config to enable tracking

experiment:
  name: "coral_x_with_emergent_tracking"
  dataset:
    provider: "quixbugs_real"
    training_problems: []  # Your existing training problems
  model:
    name: "codellama/CodeLlama-7b-Python-hf"

# ADD THIS SECTION to enable emergent behavior tracking
emergent_tracking:
  enabled: true                          # Enable simple emergent behavior detection
  output_dir: "results/emergent_simple"  # Where to save tracking data
  alert_threshold: 0.8                   # Confidence threshold for alerts
  save_frequency: 20                     # Save progress every N evaluations

# Your existing config sections remain unchanged
evo:
  population_size: 20
  generations: 10
  rank_candidates: [4, 8, 16, 32]
  alpha_candidates: [8.0, 16.0, 32.0]
  dropout_candidates: [0.05, 0.1, 0.2]
  target_modules: ["q_proj", "v_proj"]

evaluation:
  fitness_weights:
    bugfix: 0.6
    style: 0.2
    security: 0.1
    runtime: 0.1

generation:
  max_tokens: 512
  temperature: 0.7

# Optional: Track current generation for better behavior analysis
execution:
  current_generation: 0  # This gets updated automatically during evolution 