execution:
  generations: 10
  held_out_benchmark_config:
    enabled: true
    fail_on_benchmark_error: false
    run_after_evolution: true
    save_combined_results: true
  population_size: 20
  run_held_out_benchmark: true
  selection_mode: pareto
experiment:
  dataset:
    path: /cache/quixbugs_dataset
  model:
    name: codellama/CodeLlama-7b-Python-hf
infra:
  executor: modal
